# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9996aafa769d8211c21d802630a581b8d1d69e1d15a282b77f764152c08a6366146219d35bbdcc0afa5a9f0acab49441cb0b09ba3f0a38581fa3eefe75e06a62

test:
  secret_key_base: ef785f83bb590a227f0538414ecd2c52e2cf6e24d671feb3ab267c415905ea7a1e1dc608d41725a95176ff7fcf67d5e15b1a1b941dc613d9a1691c7a8edd43a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
